---
# Master Playbook để chạy toàn cụm (Sử dụng Roles)

- name: Nhóm 1 - Hạ tầng cơ bản (Java, Conda)
  hosts: all
  become: yes
  roles:
    - java
    - conda

- name: Nhóm 2 - Lõi Big Data (HDFS, Spark)
  hosts: all
  become: yes
  roles:
    - hadoop
    - spark

- name: Nhóm 3 - Data Warehouse (ClickHouse)
  hosts: storage
  become: yes
  roles:
    - clickhouse

- name: Nhóm 4 - Quản lý và Điều phối (dbt, Airflow)
  hosts: master
  become: yes
  roles:
    - dbt
    - airflow
