name: 'tech_trend_dbt'
version: '1.0.0'
config-version: 2

profile: 'tech_trend_dbt'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

models:
  tech_trend_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
      
vars:
  weight_reaction: 1
  weight_comment: 2
  weight_view: 0.01