tech_trend_dbt:
  target: dev
  outputs:
    dev:
      type: clickhouse
      driver: http
      host: clickhouse
      port: 8123
      user: root
      password: root
      schema: tech_radar
      threads: 4
